### ISSUE TITLE
Duplicate interface definition of GTMSessionFetcher using Google Api with Google Sign-in pod

### ISSUE THREAD

**Issue by mrigo** [google/google-api-objectivec-client#167] opened 2016-03-22 18:48 UTC
Hi guys!
I'm using Google Sign-in with cocoapods and google-api-objectivec-client as described in the [wizard](https://developers.google.com/google-apps/calendar/quickstart/ios) for use it with the calendar API.
I need Google Sign-in to authenticate the user on my server and the google-api of the calendar to list the calendars in my iOS App.
I would like to use only the google sign-in procedure and then using the tokens to authenticate the google-api and then use the calendar API.
I can get the `GIDSignIn` and the `GIDGoogleUser` and I want to convert this info in a `GTMOAuth2Authentication`.
Then I can pass the `GTMOAuth2Authentication` to a GTLServiceCalendar service in another controller and use it.
The problem is that when I include the GTMOAuth2Authentication.h files in both the controller (one for the google sign-in authentication and one for the calendars list view) I get a lot of errors like:

```
In file included from /GoogleCalendarsListTableViewController.m:10:
In file included from ../google-api-objectivec-client/Deps/gtm-oauth2/Source/GTMOAuth2Authentication.h:33:
../google-api-objectivec-client/Deps/gtm-session-fetcher/Source/GTMSessionFetcher.h:431:1: error: duplicate interface definition for class 'GTMSessionFetcherUserDefaultsFactory'
@interface GTMSessionFetcherUserDefaultsFactory : NSObject
^
In file included from /GoogleCalendarsListTableViewController.m:9:
In file included from /GoogleCalendarsListTableViewController.h:10:
In file included from /google-api-objectivec-client/Source/Services/Calendar/Generated/GTLCalendar.h:56:
In file included from /google-api-objectivec-client/Source/Services/Calendar/Generated/GTLServiceCalendar.h:32:
In file included from /Users/Mattia/Library/Developer/Xcode/DerivedData/mirrrIOS-ayktzjshqvwacecoruzxdcqxxoqq/Build/Products/Debug-iphonesimulator/GTL.framework/Headers/GTLService.h:58:
/Users/Mattia/Library/Developer/Xcode/DerivedData/mirrrIOS-ayktzjshqvwacecoruzxdcqxxoqq/Build/Products/Debug-iphonesimulator/GTL.framework/Headers/GTMSessionFetcher.h:444:12: note: previous definition is here
@interface GTMSessionFetcherUserDefaultsFactory : NSObject
           ^
In file included from /GoogleCalendarsListTableViewController.m:10:
In file included from ../google-api-objectivec-client/Deps/gtm-oauth2/Source/GTMOAuth2Authentication.h:33:
../google-api-objectivec-client/Deps/gtm-session-fetcher/Source/GTMSessionFetcher.h:441:28: error: redefinition of 'GTMSessionFetcherError'
typedef NS_ENUM(NSInteger, GTMSessionFetcherError) {
                           ^
In file included from /GoogleCalendarsListTableViewController.m:9:
In file included from /GoogleCalendarsListTableViewController.h:10:
In file included from /google-api-objectivec-client/Source/Services/Calendar/Generated/GTLCalendar.h:56:
In file included from /google-api-objectivec-client/Source/Services/Calendar/Generated/GTLServiceCalendar.h:32:
In file included from /Users/Mattia/Library/Developer/Xcode/DerivedData/mirrrIOS-ayktzjshqvwacecoruzxdcqxxoqq/Build/Products/Debug-iphonesimulator/GTL.framework/Headers/GTLService.h:58:
/Users/Mattia/Library/Developer/Xcode/DerivedData/mirrrIOS-ayktzjshqvwacecoruzxdcqxxoqq/Build/Products/Debug-iphonesimulator/GTL.framework/Headers/GTMSessionFetcher.h:454:28: note: previous definition is here
typedef NS_ENUM(NSInteger, GTMSessionFetcherError) {
                           ^
In file included from /GoogleCalendarsListTableViewController.m:10:
In file included from ../google-api-objectivec-client/Deps/gtm-oauth2/Source/GTMOAuth2Authentication.h:33:
../google-api-objectivec-client/Deps/gtm-session-fetcher/Source/GTMSessionFetcher.h:442:3: error: redefinition of enumerator 'GTMSessionFetcherErrorDownloadFailed'
  GTMSessionFetcherErrorDownloadFailed = -1,
  ^
In file included from /GoogleCalendarsListTableViewController.m:9:
In file included from /GoogleCalendarsListTableViewController.h:10:
In file included from /google-api-objectivec-client/Source/Services/Calendar/Generated/GTLCalendar.h:56:
In file included from /google-api-objectivec-client/Source/Services/Calendar/Generated/GTLServiceCalendar.h:32:
In file included from /Users/Mattia/Library/Developer/Xcode/DerivedData/mirrrIOS-ayktzjshqvwacecoruzxdcqxxoqq/Build/Products/Debug-iphonesimulator/GTL.framework/Headers/GTLService.h:58:
/Users/Mattia/Library/Developer/Xcode/DerivedData/mirrrIOS-ayktzjshqvwacecoruzxdcqxxoqq/Build/Products/Debug-iphonesimulator/GTL.framework/Headers/GTMSessionFetcher.h:455:3: note: previous definition is here
  GTMSessionFetcherErrorDownloadFailed = -1,
  ^
In file included from /GoogleCalendarsListTableViewController.m:10:
In file included from ../google-api-objectivec-client/Deps/gtm-oauth2/Source/GTMOAuth2Authentication.h:33:
../google-api-objectivec-client/Deps/gtm-session-fetcher/Source/GTMSessionFetcher.h:443:3: error: redefinition of enumerator 'GTMSessionFetcherErrorUploadChunkUnavailable'
  GTMSessionFetcherErrorUploadChunkUnavailable = -2,
...
```

And so on...

Any solution?

Thanks in advance!
\m

**Comment by thomasvl** [comment] 2016-03-22 19:38
So I think if you switch to picking up this library via cocoapods, things might "just work" because of the defines we do.  If you are picking it up manually, you'll likely need to manually make some of the defines that the pods do to change how things are imported.

@perotinus for reference.

**Comment by perotinus** [comment] 2016-03-22 19:54
I think @thmasvl is right: CocoaPods should "just work".

How are you getting GTL.framework in your BuildProducts directory? It looks like it has headers that don't belong there: GTL.framework should not have GTMSessionFetcher headers inside it.

**Comment by thomasvl** [comment] 2016-03-22 19:56
The GTL.framework framework the checked in project file generates include the fetcher code and headers to make manual project usage easier.  It's this mix of manual and pods that I think is the cause of the issues.

**Comment by mrigo** [comment] 2016-03-23 16:01
Hi, only a quick response about my issue!
In the [google docs](https://developers.google.com/google-apps/calendar/quickstart/ios#step_2_download_the_google_client_library) there's any clue about the possibility to use it with cocoapod so I've used that guide.
Using cocoapod for every library all work like a charm!
Thanks to you all!

**Comment by thomasvl** [comment] 2016-03-23 16:47
Yea, the pod is very new, so things haven't been updated.

**Closed by thomasvl** 2016-03-23 16:47 UTC
