### ISSUE TITLE
Error: value of type 'GTLRYouTubeService' has no member 'authorizer'

### ISSUE THREAD

**Issue by manjunathgudisi** [google/google-api-objectivec-client#221] opened 2017-06-13 10:58 UTC
Hi,

My pod file is like below.

`pod 'GoogleAPIClientForREST/YouTube'`

after I do **pod update**, version of GoogleAPIClientForREST is:

`Installing GoogleAPIClientForREST (1.3.0)`

Code:

```
var service: GTLRYouTubeService
    
    public func Authorize(authentication: GIDAuthentication) {
        service.authorizer = authentication.fetcherAuthorizer()
    }
```

Getting below error when I build the project.

`error: value of type 'GTLRYouTubeService' has no member 'authorizer'`

Any help please.

**Comment by thomasvl** [comment] 2017-06-13 12:03
It almost sounds like you don't have `GTLRYouTubeService.h` in your bridging header and maybe just have `@class GTLRYouTubeService`.  If the full header is there, they it will know it is a [subclass of `GTLRService`](https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/GeneratedServices/YouTube/GTLRYouTubeService.h#L76), and [`GTLRService` provides the `authorizer`](https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/Objects/GTLRService.h#L275).

**Comment by manjunathgudisi** [comment] 2017-06-14 08:57
I have given in brdigeing file already. Still getting the same error. I have changed the **framework search path** in build settings as well, but no luck.

`#import <GoogleAPIClientForRest/GTLRYouTube.h>`

**Comment by thomasvl** [comment] 2017-06-14 12:18
Can you set up a simple example project that shows it?  At the moment I'm at a loss since I haven't seen this before.

**Comment by thomasvl** [comment] 2017-06-22 13:56
btw - this if filed on GTL, not [GTLR](https://github.com/google/google-api-objectivec-client-for-rest).  I'm going to close this out since it is the wrong project, go ahead and reopen on the correct one.

**Closed by thomasvl** 2017-06-22 13:56 UTC

**Comment by huongtran84** [comment] 2017-07-21 17:00
I also facing with the bug. how to fix it?

**Comment by manjunathgudisi** [comment] 2017-07-24 04:42
@huongtran84 look at attached podfile.lock file
![screen shot 2017-07-24 at 10 11 30 am](https://user-images.githubusercontent.com/6059076/28508448-8fef2a40-7058-11e7-8e7a-89b751282ca9.jpg)

**Comment by thomasvl** [comment] 2017-07-26 17:54
First up, please note this [project has been deprecated](https://github.com/google/google-api-objectivec-client#warning-deprecation-notice) in favor of [GTLR](https://github.com/google/google-api-objectivec-client-for-rest) \(_Note:_ there is a [Migrating From GTL to GTLR doc](https://github.com/google/google-api-objectivec-client-for-rest/wiki/Migrating-From-GTL-to-GTLR)\).

The issue is likely the use of a Swift bridging header.  Sadly, bridging headers will strip all properties, methods, etc. that reference an "incomplete" type.  Incomplete is caused simply by things being forward declared (@class Foo, @protocol DoSomething).  To have the properties exposed, you have to manually import the header that define the forward declared types:

Try adding:
  #import <GTMSessionFetcher/GTMSessionFetcher.h>		
  #import <GTMSessionFetcher/GTMSessionFetcherService.h>

That should fix the problem.  When you hit this sorta issue in ObjC, it can kick out an error about the type of the property being incomplete, but with a bridging header it just drops them leaving it in this confusing state when you try to access them.

**Comment by wuv1982** [comment] 2019-01-29 13:49
Explicitly add `import GTMSessionFetcher` in Swift
