### ISSUE TITLE
Duplicate interface definition

### ISSUE THREAD

**Issue by mikaelbartlett** [google/google-api-objectivec-client#103] opened 2015-10-16 13:45 UTC
When using framework with cocoapods with mixed Swift and Objective-C pods we have to use use_frameworks!. But when activating this I get an duplicate interface definition error:

Pods/Google-API-Client/Source/Objects/GTLService.m:86:1: Duplicate interface definition for class 'GTMHTTPUploadFetcher'

**Comment by JoeShi** [comment] 2015-10-28 04:49
I also get this error, any solution?

**Comment by ndonald2** [comment] 2015-12-01 15:22
As discussed in #83, there seems to be an issue with using `use_frameworks!`. Hopefully Google pays attention to this and sorts it out, because that is very frustrating.

**Comment by PierreMardon** [comment] 2016-01-28 17:44
Same error here, no satisfying workaround (no way not using dependencies management), hope some dev will have a look at this soon.

**Comment by thomasvl** [comment] 2016-01-28 18:00
Fyi - The pod you are using isn't by use, Issue #79 is open for adding podspecs here.

To do this right, and avoid the duplicate symbols, I'm working through getting them in on the projects this project depends on (fetcher, oauth2).

**Comment by PierreMardon** [comment] 2016-01-29 08:38
Oh, can't believe I did miss this issue.
Bon courage then !!

**Comment by eranmarom** [comment] 2016-03-24 17:37
Any solution to this yet? Any workaround that still uses the CocoaPods system?

**Comment by thomasvl** [comment] 2016-03-24 17:40
The original issue came from using a cocoapod by a third party.  We now have a pod in the project (https://github.com/google/google-api-objectivec-client/blob/master/GoogleAPIClient.podspec) and as far as we know, no problems with duplicates using that pod.

@eranmarom which pod are you using?

**Comment by thomasvl** [comment] 2016-03-24 17:41
Closing this as I believe the problem is resolved if you are using the official pod.

**Closed by thomasvl** 2016-03-24 17:41 UTC

**Comment by eranmarom** [comment] 2016-03-27 08:56
I used the following pod, which I thought was the official
pod 'Google-API-Client/Drive', '~> 1.0'

**Comment by thomasvl** [comment] 2016-03-28 14:00
The quick starts are by some other teams internally, but yes, hopefully they will get updated shortly to use pods.

**Comment by srinathp90** [comment] 2016-11-16 04:40
Simple sollution here..

Go to edit scheme -> Select Build -> Build option untick the Parallelize Build

Now run your App
