### ISSUE TITLE
Include the podspec in this repository

### ISSUE THREAD

**Issue by 0xced** [google/google-api-objectivec-client#110] opened 2015-11-01 13:17 UTC
The `Google-API-Client` podspec should be included in this repository.

I’m trying to use my `fix-resourceId` branch with this Podfile:

```ruby
pod 'Google-API-Client/YouTube', { :git => 'https://github.com/0xced/google-api-objectivec-client', :branch => 'fix-resourceId' }
```

Unfortunately, doing `pod install` fails with the following error because of the missing podspec:
```
Fetching external sources
-> Pre-downloading: `Google-API-Client` from `https://github.com/0xced/google-api-objectivec-client`, branch `fix-resourceId`
 > Git download
 > Git download
     $ /opt/local/bin/git clone https://github.com/0xced/google-api-objectivec-client /var/folders/1l/rbhqr1jx4fdbgxmf58vwdw700000gq/T/d20151101-46272-wcy14c --single-branch --depth 1
     --branch fix-resourceId
     Cloning into '/var/folders/1l/rbhqr1jx4fdbgxmf58vwdw700000gq/T/d20151101-46272-wcy14c'...
[!] Unable to find a specification for 'Google-API-Client'.
```

**Comment by thomasvl** [comment] 2016-01-05 15:38
Duplicate of issue #79

**Closed by thomasvl** 2016-01-05 15:38 UTC
