### ISSUE TITLE
Cannot build with frameworks: duplicate interface definition and include of non-modular header

### ISSUE THREAD

**Issue by SSheldon** [google/google-api-objectivec-client#162] opened 2016-03-10 23:49 UTC
Hi! First off many thanks for adding a Podspec in #157, I'm excited to use this library from the official source so that it's easy to update.

Currently, this library will not build if `use_frameworks!` is enabled in CocoaPods. This is an issue because anyone who wants to use Swift in their pods must enable `use_frameworks!`. A podfile that repros this:
``` ruby
platform :ios, '8.0'
use_frameworks!

target 'PodsTest' do
  pod 'GoogleAPIClient/Plus', '1.0.0'
end
```

If I install this podfile and try to build, I get lots of errors from the redefinition of `GTLUploadFetcherClass` in `GTLService.m`:
```
Pods/GoogleAPIClient/Source/Objects/GTLService.m:86:1: error: duplicate interface definition for class 'GTMSessionUploadFetcher'
@interface GTLUploadFetcherClass : GTMBridgeFetcher
^
In module 'GTMSessionFetcher' imported from Pods/GoogleAPIClient/Source/Objects/GTLService.h:50:
Pods/GTMSessionFetcher/Source/GTMSessionUploadFetcher.h:64:12: note: previous definition is here
@interface GTMSessionUploadFetcher : GTMSessionFetcher
           ^
Pods/GoogleAPIClient/Source/Objects/GTLService.m:99:26: error: property has a previous declaration
@property(strong) NSURL *uploadLocationURL;
                         ^
In module 'GTMSessionFetcher' imported from Pods/GoogleAPIClient/Source/Objects/GTLService.h:50:
Pods/GTMSessionFetcher/Source/GTMSessionUploadFetcher.h:94:40: note: property declared here
@property(strong, GTM_NULLABLE) NSURL *uploadLocationURL;
                                       ^
Pods/GoogleAPIClient/Source/Objects/GTLService.m:100:27: error: property has a previous declaration
@property(strong) NSData *uploadData;
                          ^
In module 'GTMSessionFetcher' imported from Pods/GoogleAPIClient/Source/Objects/GTLService.h:50:
Pods/GTMSessionFetcher/Source/GTMSessionUploadFetcher.h:95:41: note: property declared here
@property(strong, GTM_NULLABLE) NSData *uploadData;
                                        ^
Pods/GoogleAPIClient/Source/Objects/GTLService.m:101:26: error: property has a previous declaration
@property(strong) NSURL *uploadFileURL;
                         ^
In module 'GTMSessionFetcher' imported from Pods/GoogleAPIClient/Source/Objects/GTLService.h:50:
Pods/GTMSessionFetcher/Source/GTMSessionUploadFetcher.h:96:40: note: property declared here
@property(strong, GTM_NULLABLE) NSURL *uploadFileURL;
                                       ^
Pods/GoogleAPIClient/Source/Objects/GTLService.m:102:33: error: property has a previous declaration
@property(strong) NSFileHandle *uploadFileHandle;
                                ^
In module 'GTMSessionFetcher' imported from Pods/GoogleAPIClient/Source/Objects/GTLService.h:50:
Pods/GTMSessionFetcher/Source/GTMSessionUploadFetcher.h:97:47: note: property declared here
@property(strong, GTM_NULLABLE) NSFileHandle *uploadFileHandle;
```

There is another set of errors from `GTLService.h`, where it imports things from GTMSessionFetcher:
```
In file included from Build/Products/Debug-iphonesimulator/GoogleAPIClient/GoogleAPIClient.framework/Headers/GoogleAPIClient-umbrella.h:11:
Build/Products/Debug-iphonesimulator/GoogleAPIClient/GoogleAPIClient.framework/Headers/GTLService.h:50:11: error: include of non-modular header inside framework module 'GoogleAPIClient.GTLService' [-Werror,-Wnon-modular-include-in-framework-module]
  #import "GTMSessionFetcher.h"
          ^
Build/Products/Debug-iphonesimulator/GoogleAPIClient/GoogleAPIClient.framework/Headers/GTLService.h:51:11: error: include of non-modular header inside framework module 'GoogleAPIClient.GTLService' [-Werror,-Wnon-modular-include-in-framework-module]
  #import "GTMSessionFetcherService.h"
          ^
2 errors generated.
```

I can fix these issues by editing the pod with this diff:
``` diff
diff --git a/Pods/GoogleAPIClient/Source/Objects/GTLService.h b/Pods/GoogleAPIClient/Source/Objects/GTLService.h
index 9fd09bb..389ca38 100644
--- a/Pods/GoogleAPIClient/Source/Objects/GTLService.h
+++ b/Pods/GoogleAPIClient/Source/Objects/GTLService.h
@@ -47,8 +47,8 @@
   #define GTLUploadFetcherClass GTMSessionUploadFetcher
   #define GTLUploadFetcherClassStr @"GTMSessionUploadFetcher"
 
-  #import "GTMSessionFetcher.h"
-  #import "GTMSessionFetcherService.h"
+  #import <GTMSessionFetcher/GTMSessionFetcher.h>
+  #import <GTMSessionFetcher/GTMSessionFetcherService.h>
 #else
   // !GTL_USE_SESSION_FETCHER
   #define GTLUploadFetcherClass GTMHTTPUploadFetcher
diff --git a/Pods/GoogleAPIClient/Source/Objects/GTLService.m b/Pods/GoogleAPIClient/Source/Objects/GTLService.m
index f133218..76ee3eb 100644
--- a/Pods/GoogleAPIClient/Source/Objects/GTLService.m
+++ b/Pods/GoogleAPIClient/Source/Objects/GTLService.m
@@ -79,50 +79,7 @@ static NSString *ETagIfPresent(GTLObject *obj) {
 }
 @end
 
-// If the upload fetcher class is available, it can be used for chunked uploads
-//
-// We locally declare some methods of the upload fetcher so we
-// do not need to import the header, as some projects may not have it available
-@interface GTLUploadFetcherClass : GTMBridgeFetcher
-
-#if GTL_USE_SESSION_FETCHER
-+ (instancetype)uploadFetcherWithRequest:(NSURLRequest *)request
-                          uploadMIMEType:(NSString *)uploadMIMEType
-                               chunkSize:(int64_t)chunkSize
-                          fetcherService:(GTMSessionFetcherService *)fetcherServiceOrNil;
-
-+ (instancetype)uploadFetcherWithLocation:(NSURL *)uploadLocationURL
-                           uploadMIMEType:(NSString *)uploadMIMEType
-                                chunkSize:(int64_t)chunkSize
-                           fetcherService:(GTMSessionFetcherService *)fetcherServiceOrNil;
-
-@property(strong) NSURL *uploadLocationURL;
-@property(strong) NSData *uploadData;
-@property(strong) NSURL *uploadFileURL;
-@property(strong) NSFileHandle *uploadFileHandle;
-#else
-+ (instancetype)uploadFetcherWithRequest:(NSURLRequest *)request
-                              uploadData:(NSData *)data
-                          uploadMIMEType:(NSString *)uploadMIMEType
-                               chunkSize:(NSUInteger)chunkSize
-                          fetcherService:(GTMBridgeFetcherService *)fetcherService;
-+ (instancetype)uploadFetcherWithRequest:(NSURLRequest *)request
-                        uploadFileHandle:(NSFileHandle *)uploadFileHandle
-                          uploadMIMEType:(NSString *)uploadMIMEType
-                               chunkSize:(NSUInteger)chunkSize
-                          fetcherService:(GTMBridgeFetcherService *)fetcherService;
-// Use the old fetcher.
-+ (instancetype)uploadFetcherWithLocation:(NSURL *)location
-                         uploadFileHandle:(NSFileHandle *)fileHandle
-                           uploadMIMEType:(NSString *)uploadMIMEType
-                                chunkSize:(NSUInteger)chunkSize
-                           fetcherService:(GTMBridgeFetcherService *)fetcherService;
-#endif  // GTL_USE_SESSION_FETCHER
-
-- (void)pauseFetching;
-- (void)resumeFetching;
-- (BOOL)isPaused;
-@end
+#import <GTMSessionFetcher/GTMSessionUploadFetcher.h>
 
 
 @interface GTLService ()
```

But I assume these changes would wreak havoc on your internal builds :) Any suggestions on a good way to solve this?

**Comment by tswast** [comment] 2016-03-11 00:02
@jayneflux Could you investigate? I haven't used Swift much.

**Comment by SSheldon** [comment] 2016-03-11 00:04
@tswast to be clear my repro project doesn't include any Swift, just Objective-C :)

Swift is just the primary motivation that someone would enable `use_frameworks!` (although frameworks also have the advantage of sharing the binary between app and extensions, no duplication required)

I'm happy to publish a repo with an example project if that'd help with your investigations

**Comment by jayneflux** [comment] 2016-03-11 01:30
@perotinus has been exploring similar issues for GTMOAuth2.

**Comment by SSheldon** [comment] 2016-03-11 01:40
@tswast example project available here: https://github.com/SSheldon/GoogleAPIClient162

**Comment by SSheldon** [comment] 2016-03-11 01:47
P.S. @perotinus if you want to publish GTMOAuth2 as is and fix the framework issues as a followup, you can run the lint with `--use-libraries`. Compiling with libraries instead of frameworks means the non-module imports aren't an issue.

**Comment by perotinus** [comment] 2016-03-11 05:24
@Ssheldon Good point. I tried that, and found another issue that will prevent us from pushing now: the GTMOAuth2 podspec can be deployed to 6, but GTMSessionFetcher requires 7. I'll follow up with the repo owner, and hopefully we can figure out what we want to do tomorrow. I'll report back here with an update on the issues that you've pointed out in this issue.

**Comment by perotinus** [comment] 2016-03-12 02:20
@SSheldon I've pushed the GTMOAuth2 Podspec with some updates that should allow it as both a library and a framework. I tested it locally both ways, and was able to compile an app target. I should be able to apply a similar fix here.

I'm still trying to work out the other issue, with the duplicate declaration. I'm going to try to replicate the failure in a project and see what I can find.

**Comment by SSheldon** [comment] 2016-03-12 02:31
Nice @perotinus, that looks like a good way to fix it :) This project already has the [`GTL_BUILT_AS_FRAMEWORK` preprocessor definition](https://github.com/google/google-api-objectivec-client/blob/3fa1428860fbfbd6644e1408857282f910689876/Source/Services/Plus/Generated/GTLServicePlus.h#L31), but I'm not sure under what situations that'd be used.

Let me know if there's anything I can do to help you replicate the issue.

**Comment by perotinus** [comment] 2016-03-12 03:13
OK, I think I understand why the duplicate declaration issue is happening. If you integrate as frameworks instead of libraries, importing GTMSessionFetcher.h brings the entire module along for the ride, which brings along the GTMSessionUploadFetcher declaration, which causes the duplicate declaration error.

**Comment by tswast** [comment] 2016-03-22 00:45
@perotinus or @jayneflux Would you mind making the fix for this? I don't have time to work on this.

**Comment by SSheldon** [comment] 2016-03-22 00:47
@perotinus fixed this in #163 and @thomasvl is prepping a new 1.0.1 release :)

**Comment by thomasvl** [comment] 2016-03-22 12:51
v1.0.1 cut.  This should fix things for you.

**Closed by thomasvl** 2016-03-22 12:51 UTC

**Comment by mrigo** [comment] 2016-03-22 18:00
Hi guys!
I've a similar problem.
I'm using Google Sign-in with cocoapods and google-api-objectivec-client as described in the [wizard](https://developers.google.com/google-apps/calendar/quickstart/ios) for use it with the calendar API.
I need Google Sign-in to authenticate the user on my server and the google-api of the calendar to list the calendars in my iOS App.
I would like to use only the google sign-in procedure and then using the tokens to authenticate the google-api and then use the calendar API.
I can get the `GIDSignIn` and the `GIDGoogleUser` and I want to convert this info in a `GTMOAuth2Authentication`.
Then I can pass the `GTMOAuth2Authentication` to a GTLServiceCalendar service in another controller and use it.
The problem is that when I include the GTMOAuth2Authentication.h files in both the controller (one for the google sign-in authentication and one for the calendars list view) I get a lot of errors like:

```
In file included from /GoogleCalendarsListTableViewController.m:10:
In file included from ../google-api-objectivec-client/Deps/gtm-oauth2/Source/GTMOAuth2Authentication.h:33:
../google-api-objectivec-client/Deps/gtm-session-fetcher/Source/GTMSessionFetcher.h:431:1: error: duplicate interface definition for class 'GTMSessionFetcherUserDefaultsFactory'
@interface GTMSessionFetcherUserDefaultsFactory : NSObject
^
In file included from /GoogleCalendarsListTableViewController.m:9:
In file included from /GoogleCalendarsListTableViewController.h:10:
In file included from /google-api-objectivec-client/Source/Services/Calendar/Generated/GTLCalendar.h:56:
In file included from /google-api-objectivec-client/Source/Services/Calendar/Generated/GTLServiceCalendar.h:32:
In file included from /Users/Mattia/Library/Developer/Xcode/DerivedData/mirrrIOS-ayktzjshqvwacecoruzxdcqxxoqq/Build/Products/Debug-iphonesimulator/GTL.framework/Headers/GTLService.h:58:
/Users/Mattia/Library/Developer/Xcode/DerivedData/mirrrIOS-ayktzjshqvwacecoruzxdcqxxoqq/Build/Products/Debug-iphonesimulator/GTL.framework/Headers/GTMSessionFetcher.h:444:12: note: previous definition is here
@interface GTMSessionFetcherUserDefaultsFactory : NSObject
           ^
In file included from /GoogleCalendarsListTableViewController.m:10:
In file included from ../google-api-objectivec-client/Deps/gtm-oauth2/Source/GTMOAuth2Authentication.h:33:
../google-api-objectivec-client/Deps/gtm-session-fetcher/Source/GTMSessionFetcher.h:441:28: error: redefinition of 'GTMSessionFetcherError'
typedef NS_ENUM(NSInteger, GTMSessionFetcherError) {
                           ^
In file included from /GoogleCalendarsListTableViewController.m:9:
In file included from /GoogleCalendarsListTableViewController.h:10:
In file included from /google-api-objectivec-client/Source/Services/Calendar/Generated/GTLCalendar.h:56:
In file included from /google-api-objectivec-client/Source/Services/Calendar/Generated/GTLServiceCalendar.h:32:
In file included from /Users/Mattia/Library/Developer/Xcode/DerivedData/mirrrIOS-ayktzjshqvwacecoruzxdcqxxoqq/Build/Products/Debug-iphonesimulator/GTL.framework/Headers/GTLService.h:58:
/Users/Mattia/Library/Developer/Xcode/DerivedData/mirrrIOS-ayktzjshqvwacecoruzxdcqxxoqq/Build/Products/Debug-iphonesimulator/GTL.framework/Headers/GTMSessionFetcher.h:454:28: note: previous definition is here
typedef NS_ENUM(NSInteger, GTMSessionFetcherError) {
                           ^
In file included from /GoogleCalendarsListTableViewController.m:10:
In file included from ../google-api-objectivec-client/Deps/gtm-oauth2/Source/GTMOAuth2Authentication.h:33:
../google-api-objectivec-client/Deps/gtm-session-fetcher/Source/GTMSessionFetcher.h:442:3: error: redefinition of enumerator 'GTMSessionFetcherErrorDownloadFailed'
  GTMSessionFetcherErrorDownloadFailed = -1,
  ^
In file included from /GoogleCalendarsListTableViewController.m:9:
In file included from /GoogleCalendarsListTableViewController.h:10:
In file included from /google-api-objectivec-client/Source/Services/Calendar/Generated/GTLCalendar.h:56:
In file included from /google-api-objectivec-client/Source/Services/Calendar/Generated/GTLServiceCalendar.h:32:
In file included from /Users/Mattia/Library/Developer/Xcode/DerivedData/mirrrIOS-ayktzjshqvwacecoruzxdcqxxoqq/Build/Products/Debug-iphonesimulator/GTL.framework/Headers/GTLService.h:58:
/Users/Mattia/Library/Developer/Xcode/DerivedData/mirrrIOS-ayktzjshqvwacecoruzxdcqxxoqq/Build/Products/Debug-iphonesimulator/GTL.framework/Headers/GTMSessionFetcher.h:455:3: note: previous definition is here
  GTMSessionFetcherErrorDownloadFailed = -1,
  ^
In file included from /GoogleCalendarsListTableViewController.m:10:
In file included from ../google-api-objectivec-client/Deps/gtm-oauth2/Source/GTMOAuth2Authentication.h:33:
../google-api-objectivec-client/Deps/gtm-session-fetcher/Source/GTMSessionFetcher.h:443:3: error: redefinition of enumerator 'GTMSessionFetcherErrorUploadChunkUnavailable'
  GTMSessionFetcherErrorUploadChunkUnavailable = -2,

```

And so on...

Any solution?

Thanks in advance!
\m

**Comment by thomasvl** [comment] 2016-03-22 18:05
You might want to spin this into a new issue since this may be a different problem because of the use of Google Sign-in.

Just confirming - are you using this library also a cocoapod, or manually wiring things in?

**Comment by mrigo** [comment] 2016-03-22 18:46
No, I'm using only Google Sign-in with cocoapod.
So, I'll open a new issue!
Thanks

**Comment by SSheldon** [comment] 2016-03-23 01:13
Hey @thomasvl, could this version be pushed to the pods trunk as well? I believe last time @perotinus was able to do that :)

**Comment by thomasvl** [comment] 2016-03-23 15:26
Yup, realized we needed to do it last night, but ran of time.  Working on it this morning.

**Comment by thomasvl** [comment] 2016-03-23 15:48
Push is failing because of min versions.  Working on sorting that out since it should have prevented the pervious one from being pushed also.

**Comment by tswast** [comment] 2016-03-23 15:57
Yeah, it did prevent me. I bumped the version for the push, but forgot to
bump it here.

*  •  **Tim Swast*
*  •  *Developer Programs Engineer
*  •  *Google Cloud DevRel
*  •  *swast@google.com
  •  +1 (512) 343-5226

On Wed, Mar 23, 2016 at 8:49 AM, Thomas Van Lenten <notifications@github.com

**Comment by mrigo** [comment] 2016-03-23 16:01
Hi, only a quick response about my issue!
In the [google docs](https://developers.google.com/google-apps/calendar/quickstart/ios#step_2_download_the_google_client_library) there's any clue about the possibility to use it with cocoapod so I've used that guide.
Using cocoapod for every library all work like a charm!
Thanks to you all!

**Comment by thomasvl** [comment] 2016-03-23 16:59
https://github.com/google/google-api-objectivec-client/pull/168 bumped the min.  Starting the push again.

**Comment by thomasvl** [comment] 2016-03-23 18:06
Ok, should be line.
